<%@ include file="includes.jsp" %>

<portal:SetContent name="ActiveTab">
  <% out.print(org.metaz.gui.portal.PortalTabTag.TAB_INFO); %>
</portal:SetContent>
<portal:SetContent name="Background">images/binocs.jpg</portal:SetContent>
<portal:SetContent name="PageContent"> Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Ut sed est. Nulla aliquet urna vitae ligula. Duis molestie convallis risus. Donec quam tortor, feugiat sit amet, congue sed, convallis sit amet, metus. Donec eleifend, sem quis placerat volutpat, elit pede aliquam nunc, euismod tincidunt leo urna non diam. Cras at arcu. Quisque ligula dui, mollis eu, euismod at, rhoncus vel, lectus. Duis malesuada scelerisque tortor. Sed pretium. Cras imperdiet consequat urna. Nunc placerat est ut orci scelerisque rhoncus. Phasellus ullamcorper interdum dolor. Integer purus sem, pellentesque a, bibendum non, tempor vel, sapien. Curabitur faucibus nunc quis augue. Donec pharetra, lacus a elementum pulvinar, nulla tortor vestibulum sapien, sit amet feugiat libero arcu vel velit. Donec vel mi. 
  
  Nulla ligula massa, sodales ut, dignissim nec, mattis quis, magna. Ut aliquam velit ac lectus. Vivamus interdum dolor mattis elit. Proin congue. Nullam metus dolor, scelerisque nec, lobortis non, semper quis, dolor. Praesent tortor odio, lacinia eu, facilisis vitae, euismod non, quam. Nam eget nibh sit amet turpis ullamcorper euismod. Morbi placerat, odio vitae euismod blandit, nunc leo gravida lorem, eu dictum neque tortor eget sapien. Suspendisse egestas turpis ornare dolor. Etiam aliquet orci. Aliquam quam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse nec erat. 
  
  Donec fermentum. Phasellus feugiat ultrices odio. In lorem massa, tempus ut, hendrerit in, convallis sit amet, ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Nullam eleifend nisl quis velit. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. In massa. Suspendisse scelerisque, nisl a convallis fringilla, massa augue lobortis sapien, eget varius dolor arcu ac sem. Nullam gravida rhoncus sem. Aliquam erat volutpat. Nulla facilisi. Integer faucibus nisi consequat augue imperdiet pellentesque. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam tincidunt, leo nec molestie eleifend, nibh tellus viverra neque, in porta lacus quam id nisi. 
  
  Mauris sed sem. Phasellus fermentum, lorem eget consectetuer molestie, felis sapien consequat velit, non feugiat orci massa vel nulla. Pellentesque viverra. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nunc consequat libero nec nulla. Nam tempor pede eget diam. Ut bibendum tortor eu erat. Vivamus enim purus, malesuada at, faucibus at, aliquam sit amet, diam. Aliquam erat volutpat. Praesent dolor. Aenean viverra nulla ornare justo. Cras non nibh nec eros hendrerit tincidunt. Curabitur dictum lacus viverra leo. Cras pharetra libero eget sapien. Proin nec risus ut ante faucibus venenatis. 
  
  Aenean metus arcu, rutrum at, vehicula ac, aliquam vitae, elit. Integer mauris. Maecenas sed nulla. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In nec eros nec nunc tincidunt pulvinar. Integer rhoncus nisl a odio consectetuer consectetuer. Nulla facilisi. Fusce sed magna. Suspendisse scelerisque mi. Vestibulum ullamcorper diam at nulla. Curabitur at orci. Quisque rutrum euismod quam. Donec sit amet metus. In quis turpis a lacus interdum imperdiet. Fusce lectus purus, cursus in, ornare a, gravida consequat, lorem. Vestibulum tellus nisl, adipiscing sed, commodo sed, nonummy vitae, turpis. Etiam congue ullamcorper lectus. Nunc commodo. Vestibulum turpis. Pellentesque a nunc at lacus condimentum consequat. </portal:SetContent>
<%@ include file="template.jsp" %>
