package org.metaz.util;

import java.io.File;

import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerConfigurationException;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.TransformerFactoryConfigurationError;
import javax.xml.transform.stream.StreamResult;
import javax.xml.transform.stream.StreamSource;

/**
 * @author E.J. Spaans
 * 
 * Generates an autogeneratedcp.bat (cp.bat autogenerated) file based on the
 * Maven project.xml (Maven POM). Run autogeneratedcp.bat from a command line,
 * and the CLASSPATH environment variable will be set correctly according to the
 * dependencies defined.
 * 
 * The generated file expects an environment variable of MAVEN_HOME_LOCAL to be
 * set to the directory where the Maven repository is located.
 * So if your repository directory is C:\development\maven\repository, the
 * MAVEN_HOME_LOCAL directory is expected to be C:\development\maven (so without
 * the repository part).
 * 
 * If your CLASSPATH is empty, or does not exist when generating autogeneratedcp.bat,
 * your CLASSPATH wil start with an ';' (meant to terminate an existing CLASSPATH).
 * This should not cause any problems, though.
 * 
 */
public class CpBatGenerator {

	private void createCpBatFile() {
		try {
			StreamSource xsltSource = new StreamSource(new File(
					"src/main/resources/xslt/cpbat.xslt"));
			StreamSource xmlSource = new StreamSource(new File("project.xml"));
			Transformer t = TransformerFactory.newInstance().newTransformer(
					xsltSource);
			StreamResult cpBatResult = new StreamResult(new File(
					"src/main/config/metaz/autogeneratedcp.bat"));
			t.transform(xmlSource, cpBatResult);
		} catch (TransformerConfigurationException e) {
			e.printStackTrace();
		} catch (TransformerFactoryConfigurationError e) {
			e.printStackTrace();
		} catch (TransformerException e) {
			e.printStackTrace();
		}
	}

	/**
	 * @param args
	 */
	public static void main(String[] args) {
		System.out.println("Autogenerating autogeneratedcp.bat");
		CpBatGenerator generator = new CpBatGenerator();
		generator.createCpBatFile();
		System.out.println("Finished");
	}

}
